id: A903B4FE8
title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural Traditions
type: translation
pechas:
- IA81238A8
- I7AC876F6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:36.643485
  last_modified_at: 2023-01-04 11:56:36.643489
  collections:
  - Gatön Ngawang Lekpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IA81238A8/A2EE: 2D93
  I7AC876F6/11EE: 2D93
